todo_controller:
  resource: ../src/UserInterface/Controller/TodoController.php
  type: annotation

rest_controller:
  resource: ../src/UserInterface/Controller/RestController.php
  type: annotation
  prefix: '/api'
  name_prefix: 'api_'
