parameters:

services:
  _defaults:
    autowire: true
    autoconfigure: true

  SwResearch\:
    resource: "../src/"
    exclude:
      - "../src/Infrastructure/Framework/Kernel.php"

  ###### --- APPLICATION --- #######

  SwResearch\Application\CommandHandler\:
    resource: "%kernel.project_dir%/src/Application/CommandHandler/"
    autoconfigure: false
    tags:
      - { name: messenger.message_handler, bus: command.bus }

  ###### --- DOMAIN --- #######

  SwResearch\Domain\TodoInterface:
    class: 'SwResearch\Infrastructure\Database\Orm\TodoOrm'
