parameters:

services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    SwResearch\:
        resource: '../src/'
        exclude:
            - '../src/Infrastructure/Framework/Kernel.php'

    SwResearch\Application\CommandHandler\:
        resource: '%kernel.project_dir%/src/Application/CommandHandler/'
        autoconfigure: false
        tags:
            - { name: messenger.message_handler, bus: command.bus }
